In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import sklearn

In [3]:
dataset = pd.read_csv('Restaurant_Reviews.tsv',delimiter = '\t',quoting =3)

In [4]:
dataset.head(5)

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [5]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

nltk.download('stopwords')
ps = PorterStemmer()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\spars\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [6]:
cleaned_reviews = []

for i in range (0,1000,1):
  cleaned = re.sub('[^a-zA-Z]',' ',dataset['Review'][i])
  cleaned = cleaned.lower()
  cleaned = cleaned.split()
  cleaned = [ps.stem(word) for word in cleaned if not word in set(stopwords.words('english'))]
  cleaned = ' '.join(cleaned)
  cleaned_reviews.append(cleaned)

In [7]:
cleaned_reviews[2]

'tasti textur nasti'

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(cleaned_reviews).toarray()

In [9]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [10]:
y = dataset['Liked'].values

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [13]:
X_train.size

1200000

In [26]:

from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
logreg.fit(X_train, y_train)

y_pred = logreg.predict_proba(X_test)

In [31]:
y_pred1 = logreg.predict(X_test)

In [32]:
y_pred1

array([0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1], dtype=int64)

In [28]:
y_pred[0]

array([0.66511823, 0.33488177])

In [34]:
for i in range(0,len(y_pred)):
    if (y_pred[i][0] < 0.20 ):
        print("5/5 Positive and 0/5 Negative")
    elif (0.20 < y_pred[i][0] < 0.40 ):
        print("4/5 Positive and 1/5 Negative")
    elif (0.40 < y_pred[i][0] < 0.60):
        print("3/5 Positive and 2/5 Negative")
    elif (0.60 < y_pred[i][0] < 0.80):
        print("2/5 Positive and 3/5 Negative")
    elif (0.80 < y_pred[i][0]):
        print("1/5 Positive and 4/5 Negative")
    elif (0.90 < y_pred[i][0]):
        print("0/5 Positive and 5/5 Negative")

2/5 Positive and 3/5 Negative
5/5 Positive and 0/5 Negative
4/5 Positive and 1/5 Negative
5/5 Positive and 0/5 Negative
3/5 Positive and 2/5 Negative
5/5 Positive and 0/5 Negative
2/5 Positive and 3/5 Negative
4/5 Positive and 1/5 Negative
1/5 Positive and 4/5 Negative
4/5 Positive and 1/5 Negative
2/5 Positive and 3/5 Negative
1/5 Positive and 4/5 Negative
3/5 Positive and 2/5 Negative
4/5 Positive and 1/5 Negative
2/5 Positive and 3/5 Negative
5/5 Positive and 0/5 Negative
1/5 Positive and 4/5 Negative
2/5 Positive and 3/5 Negative
3/5 Positive and 2/5 Negative
3/5 Positive and 2/5 Negative
4/5 Positive and 1/5 Negative
5/5 Positive and 0/5 Negative
3/5 Positive and 2/5 Negative
2/5 Positive and 3/5 Negative
1/5 Positive and 4/5 Negative
2/5 Positive and 3/5 Negative
2/5 Positive and 3/5 Negative
2/5 Positive and 3/5 Negative
4/5 Positive and 1/5 Negative
2/5 Positive and 3/5 Negative
2/5 Positive and 3/5 Negative
5/5 Positive and 0/5 Negative
2/5 Positive and 3/5 Negative
3/5 Positi